import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';
import Footer from './_layout/footer';
import AppHeader from './_layout/header';
import RootProvider from './provider';
import './styles.css';

export const metadata: Metadata = {
  title: 'NextJS Project Starter',
  description: 'Generated by create-next-app and tailwind',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body cz-shortcut-listen="true">
        <RootProvider>
          <AppHeader />
          <main>{children}</main>
          <Footer />
        </RootProvider>
      </body>
    </html>
  );
}
